name: dft-descriptors
channels:
  - conda-forge
  - defaults
dependencies:
  - python>=3.9
  - numpy
  - pandas
  - scipy
  - psutil
  - rdkit
  - mordred
  - ase
  - networkx
  - vedo
  - pip
  - pip:
    - padelpy
